### PR TITLE
test: add test for summ_fetcher.py

### LINKED ISSUE #58: add test for `src/llm_summ/summ_fetcher.py`

### PR DESCRIPTION
**Pull request by khit-mle**
Fixes #58

### CODE REVIEW

**Review by alexa313 — CHANGES_REQUESTED** [review]
The [pytest GH action](https://github.com/mlteamurfu2325/practicum-s1/actions/runs/8489075382/job/23258772972?pr=59) failed due to inability to utilize the API key to connect to the LLM server. @khit-mle you need to add it as a secret in our repo and reference it in the pytest workflow file.

**Comment by khit-mle** [comment]
> The [pytest GH action](https://github.com/mlteamurfu2325/practicum-s1/actions/runs/8489075382/job/23258772972?pr=59) failed due to inability to utilize the API key to connect to the LLM server. @khit-mle you need to add it as a secret in our repo and reference it in the pytest workflow file.

Yes. will do 👌

**Review by LenaIkra — CHANGES_REQUESTED** [review]
I agree with @alexa313, you need to set the secrets as the corresponding env variables.

**Review by LenaIkra — APPROVED** [review]
## Code Review of [PR-59](https://github.com/mlteamurfu2325/practicum-s1/pull/59) by @LenaIkra 

### Overview
- [x] The code follows the project's coding conventions and style guide.
- [x] The code is well-structured, readable, and maintainable.
- [x] The code is properly documented with clear comments and docstrings.
- [x] The code is efficient and optimized for performance, if applicable.
- [x] The code handles edge cases and potential errors gracefully.
- [x] The code is free of any security vulnerabilities or potential risks.

### Functionality
- [x] The code implements the required functionality as described in the PR description.
- [x] The code handles all expected inputs and outputs correctly.
- [x] The code integrates well with the existing codebase and does not introduce any conflicts.
- [x] The code does not introduce any new bugs or regressions.

### Testing
- [x] The code passes all existing tests and any newly added tests.
- [x] The tests cover a sufficient range of scenarios and edge cases (needed if new tests are added).
- [x] The tests are well-structured, readable, and maintainable (needed if new tests are added).

### Documentation
- [x] The code includes clear and concise comments explaining complex logic or algorithms.
- [x] The code includes docstrings for functions, classes, and modules, following the project's documentation standards.
- [x] The PR description provides a clear explanation of the changes made and their purpose.
- [x] Any necessary updates to the project's documentation (README, API docs, etc.) are included.

### Suggestions and Improvements
- [ ] Are there any areas where the code could be further optimized or improved?
- [ ] Are there any best practices or design patterns that could be applied to enhance the code?
- [ ] Are there any potential edge cases or error scenarios that have not been considered?
- [ ] Are there any additional tests that could be added to improve code coverage?

### Other Comments
@khit-mle Now everything checks out with out GH actions. I recommend we merge.

## Overall Recommendation:
- [x] Approve
- [ ] Request Changes
- [ ] Comment Only

**Review by alexa313 — APPROVED** [review]
## Code Review of [PR-59](https://github.com/mlteamurfu2325/practicum-s1/pull/59) by @alexa313 

### Overview
- [x] The code follows the project's coding conventions and style guide.
- [x] The code is well-structured, readable, and maintainable.
- [x] The code is properly documented with clear comments and docstrings.
- [x] The code is efficient and optimized for performance, if applicable.
- [x] The code handles edge cases and potential errors gracefully.
- [x] The code is free of any security vulnerabilities or potential risks.

### Functionality
- [x] The code implements the required functionality as described in the PR description.
- [x] The code handles all expected inputs and outputs correctly.
- [x] The code integrates well with the existing codebase and does not introduce any conflicts.
- [x] The code does not introduce any new bugs or regressions.

### Testing
- [x] The code passes all existing tests and any newly added tests.
- [x] The tests cover a sufficient range of scenarios and edge cases (needed if new tests are added).
- [x] The tests are well-structured, readable, and maintainable (needed if new tests are added).

### Documentation
- [x] The code includes clear and concise comments explaining complex logic or algorithms.
- [x] The code includes docstrings for functions, classes, and modules, following the project's documentation standards.
- [x] The PR description provides a clear explanation of the changes made and their purpose.
- [x] Any necessary updates to the project's documentation (README, API docs, etc.) are included.

### Suggestions and Improvements
- [ ] Are there any areas where the code could be further optimized or improved?
- [ ] Are there any best practices or design patterns that could be applied to enhance the code?
- [ ] Are there any potential edge cases or error scenarios that have not been considered?
- [ ] Are there any additional tests that could be added to improve code coverage?

### Other Comments
@khit-mle I agree with @LenaIkra, let's merge.

## Overall Recommendation:
- [x] Approve
- [ ] Request Changes
- [ ] Comment Only

**Pull request merged**
